export const PRACTICE_AREAS = [
  "Administrative Law",
  "Admiralty / Maritime Law",
  "Antitrust & Competition Law",
  "Appellate Law",
  "Arbitration & Mediation",
  "Aviation Law",
  "Banking & Finance Law",
  "Bankruptcy & Insolvency",
  "Cannabis Law",
  "Civil Rights Law",
  "Class Action Litigation",
  "Commercial Law",
  "Communications & Media Law",
  "Constitutional Law",
  "Construction Law",
  "Consumer Protection Law",
  "Corporate Law",
  "Criminal Law",
  "Data Privacy & Cybersecurity Law",
  "Education Law",
  "Elder Law",
  "Employment & Labor Law",
  "Energy & Utilities Law",
  "Entertainment & Sports Law",
  "Environmental Law",
  "Estate Planning",
  "Family Law",
  "Financial Services Regulation",
  "Food & Drug Law",
  "Gaming Law",
  "Government Contracts",
  "Government & Public Policy",
  "Health Care Law",
  "Immigration Law",
  "Insurance Law",
  "Intellectual Property Law",
  "International Law",
  "Land Use & Zoning",
  "Litigation (General)",
  "Mergers & Acquisitions",
  "Military Law",
  "Native American Law",
  "Nonprofit & Tax-Exempt Organizations",
  "Oil & Gas Law",
  "Personal Injury Law",
  "Private Equity & Venture Capital",
  "Product Liability Law",
  "Real Estate Law",
  "Securities Law",
  "Social Security Disability Law",
  "Tax Law",
  "Telecommunications Law",
  "Transportation Law",
  "Trusts & Estates",
  "White Collar Crime",
];
