-- Lawbric-native notifications.
-- Notifications are generated by app/database events and delivered with Supabase Realtime.

begin;

drop table if exists public.ghl_notification_events cascade;
drop table if exists public.notifications cascade;

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  location_id uuid not null references public.ghl_locations(id) on delete cascade,
  recipient_user_id uuid not null references public.profiles(id) on delete cascade,
  actor_user_id uuid references public.profiles(id) on delete set null,
  notification_type text not null default 'system',
  title text not null,
  message text not null default '',
  related_type text,
  related_id uuid,
  action_url text,
  metadata jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  read_at timestamp with time zone,
  created_at timestamp with time zone not null default now()
);

create index if not exists notifications_location_created_at_idx
  on public.notifications(location_id, created_at desc);

create index if not exists notifications_recipient_unread_idx
  on public.notifications(recipient_user_id, is_read, created_at desc);

create index if not exists notifications_related_idx
  on public.notifications(related_type, related_id);

alter table public.notifications enable row level security;
alter table public.notifications force row level security;

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own"
on public.notifications
for select
to authenticated
using (
  recipient_user_id = auth.uid()
  and public.can_access_location(location_id)
);

drop policy if exists "notifications_update_own_read_state" on public.notifications;
create policy "notifications_update_own_read_state"
on public.notifications
for update
to authenticated
using (
  recipient_user_id = auth.uid()
  and public.can_access_location(location_id)
)
with check (
  recipient_user_id = auth.uid()
  and public.can_access_location(location_id)
);

revoke all on table public.notifications from public, anon, authenticated;
grant select on table public.notifications to authenticated;
grant update (is_read, read_at) on table public.notifications to authenticated;
grant all on table public.notifications to service_role;

create or replace function public.set_notification_read_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.is_read = true and old.is_read = false then
    new.read_at = coalesce(new.read_at, now());
  elsif new.is_read = false then
    new.read_at = null;
  end if;

  return new;
end;
$$;

drop trigger if exists notifications_set_read_at on public.notifications;
create trigger notifications_set_read_at before update on public.notifications
for each row execute function public.set_notification_read_at();

create or replace function public.create_notification(
  p_location_id uuid,
  p_recipient_user_id uuid,
  p_title text,
  p_message text default '',
  p_notification_type text default 'system',
  p_related_type text default null,
  p_related_id uuid default null,
  p_action_url text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_id uuid;
begin
  if not (public.can_access_location(p_location_id) or public.is_admin()) then
    raise exception 'You do not have access to this location.' using errcode = '42501';
  end if;

  if not exists (
    select 1
    from public.user_locations
    where user_id = p_recipient_user_id
      and location_id = p_location_id
  ) then
    raise exception 'The notification recipient does not have access to this location.' using errcode = '42501';
  end if;

  insert into public.notifications (
    location_id,
    recipient_user_id,
    actor_user_id,
    notification_type,
    title,
    message,
    related_type,
    related_id,
    action_url,
    metadata
  )
  values (
    p_location_id,
    p_recipient_user_id,
    auth.uid(),
    coalesce(nullif(trim(p_notification_type), ''), 'system'),
    nullif(trim(p_title), ''),
    coalesce(p_message, ''),
    nullif(trim(p_related_type), ''),
    p_related_id,
    nullif(trim(p_action_url), ''),
    coalesce(p_metadata, '{}'::jsonb)
  )
  returning id into inserted_id;

  return inserted_id;
end;
$$;

create or replace function public.notify_task_assignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.assigned_user_id is null then
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if new.assigned_user_id is not distinct from old.assigned_user_id then
      return new;
    end if;
  end if;

  if new.created_by is not null and new.assigned_user_id = new.created_by then
    return new;
  end if;

  insert into public.notifications (
    location_id,
    recipient_user_id,
    actor_user_id,
    notification_type,
    title,
    message,
    related_type,
    related_id,
    action_url,
    metadata
  )
  values (
    new.location_id,
    new.assigned_user_id,
    new.created_by,
    'task.assigned',
    'Task assigned to you',
    new.title,
    'task',
    new.id,
    '/tasks',
    jsonb_build_object('task_id', new.id, 'case_id', new.case_id)
  );

  return new;
end;
$$;

drop trigger if exists tasks_notify_assignment on public.tasks;
create trigger tasks_notify_assignment after insert or update of assigned_user_id on public.tasks
for each row execute function public.notify_task_assignment();

create or replace function public.notify_case_assignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.assigned_user_id is null then
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if new.assigned_user_id is not distinct from old.assigned_user_id then
      return new;
    end if;
  end if;

  if new.created_by is not null and new.assigned_user_id = new.created_by then
    return new;
  end if;

  insert into public.notifications (
    location_id,
    recipient_user_id,
    actor_user_id,
    notification_type,
    title,
    message,
    related_type,
    related_id,
    action_url,
    metadata
  )
  values (
    new.location_id,
    new.assigned_user_id,
    coalesce(new.updated_by, new.created_by),
    'matter.assigned',
    'Matter assigned to you',
    new.case_name,
    'matter',
    new.id,
    '/case/' || new.id::text,
    jsonb_build_object('case_id', new.id, 'case_number', new.case_number)
  );

  return new;
end;
$$;

drop trigger if exists cases_notify_assignment on public.cases;
create trigger cases_notify_assignment after insert or update of assigned_user_id on public.cases
for each row execute function public.notify_case_assignment();

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
exception
  when duplicate_object then
    null;
end $$;

revoke all on function public.set_notification_read_at() from public;
revoke all on function public.create_notification(uuid, uuid, text, text, text, text, uuid, text, jsonb) from public;
revoke all on function public.notify_task_assignment() from public;
revoke all on function public.notify_case_assignment() from public;

grant execute on function public.create_notification(uuid, uuid, text, text, text, text, uuid, text, jsonb) to authenticated;
grant execute on function public.set_notification_read_at() to service_role;
grant execute on function public.notify_task_assignment() to service_role;
grant execute on function public.notify_case_assignment() to service_role;

commit;
